spring:
  config:
    import: dev-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.datasource.url}:${secret.datasource.port}/${secret.datasource.database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

jwt:
  secret: ${secret.jwt.secret_key}
  expiration: ${secret.jwt.expiration}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY:your-s3-access-key}
    secret-key: ${AWS_S3_SECRET_KEY:your-s3-secret-key}
    region: ${AWS_S3_REGION:ap-northeast-2}
    bucket-name: ${AWS_S3_BUCKET_NAME:mykku-bucket}
