spring:
  config:
    import: dev-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.datasource.url}:${secret.datasource.port}/${secret.datasource.database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

jwt:
  secret: ${secret.jwt.secret_key}
  access-token-expiration: ${secret.jwt.access_token_expiration:86400000}
  refresh-token-expiration: ${secret.jwt.refresh_token_expiration:1209600000}

aws:
  s3:
    enabled: true
    access-key: ${secret.aws.s3.access_key}
    secret-key: ${secret.aws.s3.secret_key}
    region: ${secret.aws.s3.region}
    bucket-name: ${secret.aws.s3.bucket_name}
