spring:
  config:
    import: dev-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.datasource.url}:${secret.datasource.port}/${secret.datasource.database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

google:
  oauth:
    client-id: ${secret.oauth.client-id}
    client-secret: ${secret.oauth.client-secret}
    redirect-uri: ${secret.oauth.redirect-uri}
    token-uri: ${secret.oauth.token-uri}
    user-info-uri: ${secret.oauth.user-info-uri}

jwt:
  secret: ${secret.jwt.secret_key}
  expiration: ${secret.jwt.expiration}
