= MyKKU API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
== 개요

MyKKU API 문서입니다.

=== 공통 응답 구조

모든 API는 다음과 같은 공통 응답 구조를 가집니다:

[source,json]
----
{
  "message": "응답 메시지",
  "data": {
    // 응답 데이터
  }
}
----

=== HTTP 상태 코드

|===
| 상태 코드 | 설명

| `200 OK`
| 요청 성공

| `400 Bad Request`
| 잘못된 요청

| `401 Unauthorized`
| 인증 실패

| `403 Forbidden`
| 권한 없음

| `404 Not Found`
| 리소스를 찾을 수 없음

| `500 Internal Server Error`
| 서버 오류
|===

[[auth-api]]
== 인증 API

=== 모바일 구글 로그인

모바일 앱에서 구글 액세스 토큰을 사용하여 로그인합니다.

operation::auth-mobile-login-google[snippets='http-request,request-fields,http-response,response-fields']

=== 모바일 카카오 로그인  

모바일 앱에서 카카오 액세스 토큰을 사용하여 로그인합니다.

operation::auth-mobile-login-kakao[snippets='http-request,http-response']

=== 모바일 애플 로그인

모바일 앱에서 애플 ID 토큰을 사용하여 로그인합니다.

operation::auth-mobile-login-apple[snippets='http-request,http-response']

=== 모바일 네이버 로그인

모바일 앱에서 네이버 액세스 토큰을 사용하여 로그인합니다.

operation::auth-mobile-login-naver[snippets='http-request,request-fields,http-response,response-fields']

=== 토큰 갱신

리프레시 토큰을 사용하여 새로운 액세스 토큰을 발급받습니다.

operation::auth-refresh-token[snippets='http-request,request-fields,http-response,response-fields']

[[home-api]]
== 홈 API

=== 홈 데이터 조회

operation::home[snippets='http-request,http-response,response-fields']

[[event-api]]
== 이벤트 API

=== 이벤트 생성

이벤트를 생성합니다. 이벤트 이미지와 태그도 함께 저장됩니다.

operation::event-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[feed-api]]
== 피드 API

=== 피드 목록 조회

특정 회원의 피드 목록을 페이지네이션과 함께 조회합니다.

operation::feed-list[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

=== 보드별 피드 목록 조회

특정 게시판의 피드 목록을 페이지네이션과 함께 조회합니다.

operation::feed-list-by-board[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

=== 피드 상세 조회

특정 피드의 상세 정보를 조회합니다.

operation::feed-detail[snippets='http-request,path-parameters,http-response,response-fields']

=== 피드 작성

operation::feed-create[snippets='http-request,request-headers,request-parts,http-response,response-fields']

=== 피드 댓글 목록 조회

operation::feed-comments-list[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

[[board-api]]
== 보드 API

=== 게시판 생성

operation::board-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 게시판 수정

operation::board-update[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

[[daily-message-api]]
== 데일리 메시지 API

=== 하루 덕담 목록 조회

operation::daily-message-list[snippets='http-request,query-parameters,http-response,response-fields']

=== 하루 덕담 상세 조회

operation::daily-message-detail[snippets='http-request,path-parameters,http-response,response-fields']

=== 하루 덕담 댓글 생성

operation::daily-message-comment-create[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

=== 하루 덕담 답글 생성

operation::daily-message-reply-create[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

=== 하루 덕담 댓글 수정

operation::daily-message-comment-update[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

[[fan-note-api]]
== 덕질노트 API

=== 덕질노트 목록 조회

덕질노트 목록을 페이지네이션과 함께 조회합니다. 제작일 기준 최신순으로 정렬됩니다.

operation::fan-note-list[snippets='http-request,query-parameters,http-response,response-fields']

=== 덕질노트 상세 조회

특정 덕질노트의 상세 정보와 페이지 목록을 조회합니다. 각 페이지는 S3에 저장된 이미지 URL로 구성됩니다.

operation::fan-note-detail[snippets='http-request,path-parameters,http-response,response-fields']

[[like-api]]
== 좋아요 API

=== 좋아요한 게시판 목록 조회

operation::like-board-list[snippets='http-request,request-headers,http-response,response-fields']

=== 게시판 좋아요

operation::like-board-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 게시판 좋아요 취소

operation::like-board-delete[snippets='http-request,path-parameters,request-headers,http-response']

=== 피드 좋아요

operation::like-feed-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 피드 좋아요 취소

operation::like-feed-delete[snippets='http-request,path-parameters,request-headers,http-response']

=== 댓글 좋아요

operation::like-comment-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 댓글 좋아요 취소

operation::like-comment-delete[snippets='http-request,path-parameters,request-headers,http-response']

=== 하루 덕담 댓글 좋아요

operation::like-daily-message-comment-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 하루 덕담 댓글 좋아요 취소

operation::like-daily-message-comment-delete[snippets='http-request,path-parameters,request-headers,http-response']

[[folder-api]]
== 폴더 API

=== 폴더 생성

피드 저장을 위한 폴더를 생성합니다.

operation::folder-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

==== 에러 케이스 - 중복된 폴더 이름

이미 존재하는 폴더 이름으로 생성을 시도하는 경우 발생하는 에러입니다.

operation::folder-create-error-duplicate[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 폴더 목록 조회

현재 회원이 소유한 모든 폴더를 조회합니다.

operation::folder-list[snippets='http-request,request-headers,http-response,response-fields']

=== 폴더 수정

폴더의 이름과 설명을 수정합니다.

operation::folder-update[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

==== 에러 케이스 - 폴더를 찾을 수 없음

존재하지 않는 폴더를 수정하려고 할 때 발생하는 에러입니다.

operation::folder-update-error-not-found[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

=== 폴더 삭제

폴더를 삭제합니다.

operation::folder-delete[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

[[scrap-api]]
== 스크랩 API

=== 피드 저장

피드를 특정 폴더에 저장합니다.

operation::scrap-feed-save[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

==== 에러 케이스 - 이미 저장된 피드

이미 저장된 피드를 다시 저장하려고 할 때 발생하는 에러입니다.

operation::scrap-feed-save-error-already-exists[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

=== 피드 저장 취소

저장한 피드를 취소합니다.

operation::scrap-feed-unsave[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 저장된 피드 목록 조회

저장한 피드 목록을 페이지네이션과 함께 조회합니다. 특정 폴더로 필터링할 수 있습니다.

operation::scrap-feed-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 저장된 피드 폴더 변경

저장된 피드를 다른 폴더로 이동합니다.

operation::scrap-feed-update-folder[snippets='http-request,path-parameters,request-headers,request-fields,http-response,response-fields']

=== 하루덕담 저장

하루덕담을 저장합니다.

operation::scrap-daily-message-save[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 하루덕담 저장 취소

저장한 하루덕담을 취소합니다.

operation::scrap-daily-message-unsave[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 저장된 하루덕담 목록 조회

저장한 하루덕담 목록을 페이지네이션과 함께 조회합니다.

operation::scrap-daily-message-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 이벤트 저장

이벤트를 저장합니다.

operation::scrap-event-save[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 이벤트 저장 취소

저장한 이벤트를 취소합니다.

operation::scrap-event-unsave[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 저장된 이벤트 목록 조회

저장한 이벤트 목록을 페이지네이션과 함께 조회합니다.

operation::scrap-event-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 덕질노트 저장

덕질노트를 저장합니다.

operation::scrap-fan-note-save[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 덕질노트 저장 취소

저장한 덕질노트를 취소합니다.

operation::scrap-fan-note-unsave[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== 저장된 덕질노트 목록 조회

저장한 덕질노트 목록을 페이지네이션과 함께 조회합니다.

operation::scrap-fan-note-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[preference-api]]
== 취향 API

=== 장르 취향 저장

사용자의 장르 취향을 저장합니다. 기존 장르 취향은 모두 삭제되고 새로운 취향으로 대체됩니다.

operation::preference-genre-update[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 장르 취향 조회

사용자의 저장된 장르 취향을 조회합니다.

operation::preference-genre-get[snippets='http-request,request-headers,http-response,response-fields']

=== 굿즈 취향 저장

사용자의 굿즈 취향을 저장합니다. 기존 굿즈 취향은 모두 삭제되고 새로운 취향으로 대체됩니다.

operation::preference-goods-update[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 굿즈 취향 조회

사용자의 저장된 굿즈 취향을 조회합니다.

operation::preference-goods-get[snippets='http-request,request-headers,http-response,response-fields']

=== 분위기 취향 저장

사용자의 분위기 취향을 저장합니다. 기존 분위기 취향은 모두 삭제되고 새로운 취향으로 대체됩니다.

operation::preference-mood-update[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 분위기 취향 조회

사용자의 저장된 분위기 취향을 조회합니다.

operation::preference-mood-get[snippets='http-request,request-headers,http-response,response-fields']

[[error-api]]
== 에러 응답

MyKKU API는 에러 발생 시 일관된 형식의 에러 응답을 반환합니다.

=== 에러 응답 구조

모든 에러 응답은 다음과 같은 구조를 가집니다:

[source,json]
----
{
  "message": "에러 메시지"
}
----

=== 400 Bad Request

요청이 잘못된 경우 반환됩니다. 예: 중복된 데이터, 유효하지 않은 입력값 등

operation::error-400[snippets='http-response,response-fields']

예시:
- 이미 존재하는 게시판 제목으로 생성 시도
- 이미 좋아요한 피드에 다시 좋아요 시도
- 입력값이 제한 길이를 초과하는 경우

=== 404 Not Found

요청한 리소스를 찾을 수 없는 경우 반환됩니다.

operation::error-404[snippets='http-response,response-fields']

예시:
- 존재하지 않는 게시판 ID로 조회
- 존재하지 않는 피드 ID로 조회
- 삭제된 댓글에 접근 시도

=== 500 Internal Server Error

서버 내부 오류가 발생한 경우 반환됩니다.

operation::error-500[snippets='http-response,response-fields']