ALTER TABLE member MODIFY COLUMN provider ENUM('GOOGLE', 'KAKAO', 'NAVER', 'APPLE', 'EMAIL') NULL;
ALTER TABLE member MODIFY COLUMN social_id VARCHAR(255) NULL;
ALTER TABLE member ADD COLUMN password VARCHAR(255) NULL;
ALTER TABLE member ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false;
