name: dev-cd

on:
  push:
    branches:
      - "develop"
      - "chore/#30"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Develop Branch
        uses: actions/checkout@v4
        with:
          ref: "develop"

      - name: Setting dev-secret.yml
        run: |
          echo "${{ secrets.DEV_SECRET_YML }}" > ./src/main/resources/dev-secret.yml

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean And Test With Gradle
        run: ./gradlew clean test

      - name: bootJar with Gradle
        run: ./gradlew bootJar --info

      - name: Change artifact file name
        run: mv build/libs/*.jar build/libs/app.jar

      - name: Upload artifact file
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: ./build/libs/app.jar
          if-no-files-found: error

      - name: Upload deploy scripts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-scripts
          path: ./scripts/dev/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: dev

    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ~/app

      - name: Download deploy scripts
        uses: actions/download-artifact@v4
        with:
          name: deploy-scripts
          path: ~/app/scripts

      - name: Replace application to latest
        run: sudo sh ~/app/scripts/replace-new-version.sh
