name: dev-cd

on:
  push:
    branches:
      - "develop"
      - "chore/#124"

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mykku-be
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    uses: ./.github/workflows/Dev_CI.yml

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Setting dev-secret.yml
        run: |
          echo "${{ secrets.DEV_SECRET_YML }}" > ./src/main/resources/dev-secret.yml

      - name: Setting secret-account-key-dev.json
        run: |
          echo '${{ secrets.FIREBASE_KEY_JSON }}' | base64 -d > ./src/main/resources/firebase/service-account-key-dev.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload deploy scripts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-scripts
          path: ./scripts/dev/
          if-no-files-found: error

      - name: Upload docker-compose file
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: ./docker-compose.dev.yml
          if-no-files-found: error

  deploy:
    needs: build-and-push
    runs-on: dev

    steps:
      - name: Download deploy scripts
        uses: actions/download-artifact@v4
        with:
          name: deploy-scripts
          path: ~/app/scripts

      - name: Download docker-compose file
        uses: actions/download-artifact@v4
        with:
          name: docker-compose
          path: ~/app

      - name: Deploy with Docker Compose
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export IMAGE_TAG=${{ github.sha }}
          sudo -E sh ~/app/scripts/replace-new-version.sh
