name: dev-cd

on:
  push:
    branches:
      - "develop"
      - "chore/#30"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting dev-secret.yml
        run: |
          echo "${{ secrets.DEV_SECRET_YML }}" > ./src/main/resources/dev-secret.yml

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle (skip tests)
        run: |
          # Create dummy snippets directory to avoid asciidoctor error
          mkdir -p build/generated-snippets
          
          # Build with documentation
          ./gradlew clean bootJar -x test --info

      - name: Change artifact file name
        run: |
          # Find the built jar file (excluding plain jar)
          JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "No JAR file found!"
            exit 1
          fi
          mv "$JAR_FILE" build/libs/app.jar

      - name: Upload artifact file
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: ./build/libs/app.jar
          if-no-files-found: error

      - name: Upload deploy scripts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-scripts
          path: ./scripts/dev/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: dev

    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ~/app

      - name: Download deploy scripts
        uses: actions/download-artifact@v4
        with:
          name: deploy-scripts
          path: ~/app/scripts

      - name: Replace application to latest
        run: sudo sh ~/app/scripts/replace-new-version.sh
