name: generate-docs

on:
  push:
    branches:
      - "develop"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: $
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: mykku_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: "gradle"

      - name: Grant Permission
        run: chmod +x ./gradlew

      - name: Run tests to generate snippets
        run: ./gradlew test

      - name: Generate API documentation
        run: ./gradlew asciidoctor

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/docs/asciidoc"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
